import = ["~/.config/alacritty/themes/themes/gruvbox_dark.toml"]

[font]
size = 16

[font.normal]
family = "JetBrainsMono Nerd Font"
#family = "RobotoMono Nerd Font"

[window]
decorations = "Buttonless"
opacity = 0.95

[window.padding]
x = 5
y = 5
